apiVersion: apps/v1
kind: Deployment
metadata:
  name: blau
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blau
  template:
    metadata:
      labels:
        app: blau
    spec:
      containers:
      - name: blau
        image: vpnaas/blau:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: RUST_LOG
          value: info
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: mekstack-secret
              key: blau-client-id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mekstack-secret
              key: blau-client-secret
        - name: ISSUER_URL
          valueFrom:
            secretKeyRef:
              name: mekstack-secret
              key: blau-issuer-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mekstack-secret
              key: blau-secret-key
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mekstack-secret
              key: jwt-secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: blau
spec:
  selector:
    app: blau
  ports:
  - protocol: TCP
    port: 80
